#!/usr/bin/env python
import sys

import numpy

from pylal import Fr
from pylal import frutils
from glue.lal import Cache

import lal


with open(sys.argv[1]) as cfile:
    cache1 = sorted(Cache.fromfile(cfile))
with open(sys.argv[2]) as cfile:
    cache2 = sorted(Cache.fromfile(cfile))

# FIXME: Data frames will have to be same start and duration
channel = sys.argv[3] + ":FAKE-STRAIN"
for entry1, entry2 in zip(cache1, cache2):
    d1, fr_start1, _, dt1, _, _ = frutils.frgetvect1d(entry1.path, channel) #, start, (stop-start))
    d2, fr_start2, _, dt2, _, _ = frutils.frgetvect1d(entry2.path, channel) #, start, (stop-start))

    assert numpy.round(1/dt1) == numpy.round(1/dt2)
    assert fr_start1 == fr_start2
    print "Epochs %10.5f %10.5f" % (fr_start1, fr_start2)

    print "Data RMS before addition: %1.10g, %1.10g" % (d1.std(), d2.std())
    dsum = d1 + d2
    print "Data RMS after addition: %1.10g" % dsum.std()

    start, dur = fr_start1, len(d1)*dt1
    channellist = {
        "name": "%s:FAKE-STRAIN" % (sys.argv[3]),
        "data": dsum,
        "start": fr_start1,
        "dx": dt1,
        "kind": "SIM",
        "type": 1 }

    #
    # Write frame
    #

    fname = "%s-%s_ALIGO_MDC_COMB-%d-%d.gwf" % (sys.argv[3][0], sys.argv[3], start, int(dur))
    Fr.frputvect(filename = fname, channellist = [channellist], verbose=0)
