#!/usr/bin/env python
import sys

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot
import numpy

print "Loading file %s..." % sys.argv[1]
samples = numpy.fromfile(sys.argv[1])
print "...done."
print "Samples variance: %f" % (samples.std()**2)
print "band / delta_f = %f" % (4/0.25)
print samples.std()**2

pyplot.hist(samples, normed=True, bins=20)
pyplot.grid()
pyplot.savefig("sample_hist.png")
